spring.application.name=fourcamp
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_digital
spring.datasource.username=root
spring.datasource.password=G@b5
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true